# Generated by Django 4.1 on 2022-08-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_diary_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='body',
            new_name='description',
        ),
    ]
