# Generated by Django 4.1 on 2022-08-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_diagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planet_image'),
        ),
    ]
